### ISSUE TITLE
Move linuxaccra.org to a static website

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/meetings#5]
https://linuxaccra.org has been ON-OFF. As of the time of this issue, here's the status
![image](https://github.com/user-attachments/assets/8cb2a274-ce32-4226-b120-d1bb82d63a2e)

Recommendations for static websites:
- Hugo
- Jekyll
- Pelican
- Plain HTML/CSS

cc @LinuxAccra-UserGroup/webapp-dev  Everyone

**Comment by rexfordnyrk** [comment]
Occasionally, an issue may pop up for one reason or another, that is simply technology and it is expected. This site has been running flawlessly since 2017 to date with only 3 notable issues that came up in the 7 years span. 
1. In 2022 - downtime of 2 days - Reason being the expiration of card details on file for renewal.  
2. May 2024 - A small PHP deprecation error. but no downtime
3. Now - this issue due to a false report made of malicious activity and this has been fixed. 

All of these combined does not even add up to a 0.01% downtime of the site and therefore does not warrant the need for the above notion of moving the site. The site is live as of today 9am GMT!

![Screenshot at 2024-09-25 09-09-50](https://github.com/user-attachments/assets/08987d2b-5a45-470c-8b3b-21d7725eff78)

**Comment by enockseth** [comment]
Thanks for the insights.
